version: '3.5'

services:
    php:
        container_name: marinafront_api_php
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/site
    nginx:
        container_name: marinafront_api_nginx
        build: nginx
        expose:
            - 80
        env_file:
          - .env
        volumes:
            - ./:/var/www/site
            - ./logs/nginx/:/var/log/nginx

networks:
    default:
       external:
         name: webproxy
